### ISSUE TITLE
suggestion for improvement

### ISSUE THREAD

**Issue by nesnaj-blip** [PolscienceAntwerp/flempar#3]
Dear Flempar team,

When I looked for an impossible combination of type and fact (code below for replication). The calls were made only to discover after a while that this combination wasn't possible. I did this to test the script's behavior, but perhaps it would be interesting to add a boolean that aborts the call if impossible data is asked for. To that end, I would like to give two small suggestions to save users time. Which could probably be implemented in a later stage of the project:
-add a boolean that checks whether the asked information exists before the API starts.
- provide information on the blog on what all the options encompass so users have a better sense of what to expect from the pulled data.

Anyway, great work! This will be very valuable for scholars, journalists, and many more!

Arno  

-------------------------CODE--------------------------------------------------

require(devtools)
install_github("PolscienceAntwerp/flempar")

library(flempar)
library(dplyr)
library (ggplot2)

work_b <- get_work(date_range_from="2023-05-01"
                   , date_range_to="2023-06-01"
                   ,fact = "written_questions"
                   ,type = "speech"
                   ,plen_comm="comm"
                   )

**Comment by FrederikHeylen** [comment]
Hey Arno,

Thanks for the feedback and your kind words!

- Boolean Check: Agreed, expanding the checks to ensure valid combinations would enhance efficiency. We'll look into this and aim to incorporate it in an upcoming release.

- Blog Information: Good point. We'll work to provide a matrix of all available options in a future blog, helping users understand what they can expect.

Frederik

**Comment by FrederikHeylen** [comment]
Added extra checks to ensure valid combinations. Added a dataframe which documents these possibilities (type `possibilities` in console)

**Comment by FrederikHeylen** [comment]
Added extra checks to ensure valid combinations. Added a dataframe which documents these possibilities (type `possibilities` in console)
